version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto-mqtt
    read_only: true
    restart: always
    volumes:
      - ./conf:/mosquitto/config
    ports:
      - "10001:10001"
    networks:
      - network

  backend:
    container_name: iot_backend_app
    restart: always
    read_only: true
    build:
      context: .
    volumes:
      - /app/logs
      - /app/iot
    depends_on:
      - mosquitto
    ports:
      - "8001:8000"
    networks:
      - network

networks:
  network:
    name: iot_network
